name: CI

on:
        workflow_dispatch:
                push:
                        branch:
                                - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - run: make up
